name: securellm
channels:
  - defaults
dependencies:
- python=3.11.4
- pip
- pip:
  - torch==2.0.1
  - tqdm==4.65.0
  - transformers==4.40.0
  - wandb==0.15.10
  - pandas==2.0.3
  - edist==1.2.1
  - fairscale==0.4.13
  - sentencepiece==0.1.99
  - peft==0.5.0
